- name: Download code-server legacy
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ code_server_tar_url }}"
    dest: "{{ code_server_bin_dir }}"
    extra_opts:
      - --strip-components=1
      - --wildcards
      - "*/code-server"
  register: download_code_server_legacy
  when: not code_server_exists.stat.exists or
        code_server_version.stdout != code_server_ver
