- name: Create {{ code_server_dir }}
  become: yes
  file:
    state: directory
    path: "{{ code_server_dir }}"

- name: Download code-server v3
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ code_server_tar_url }}"
    dest: "{{ code_server_dir }}"
    extra_opts:
      - --strip-components=1
  notify: Restart code-server
  when: not code_server_exists.stat.exists or
        code_server_version.stdout != code_server_ver

- name: Add {{ code_server_bin_dir }}/code-server
  become: yes
  file:
    state: link
    src: "{{ code_server_dir }}/code-server"
    dest: "{{ code_server_bin_dir }}/code-server"
    # force is required if upgrade from v1 or v2,
    # in which case dest exists and is a file.
    force: yes
  notify: Restart code-server
